// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/flowup/presentations/go_mocks/email (interfaces: Sender)

package email

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Sender interface
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *_MockSenderRecorder
}

// Recorder for MockSender (not exported)
type _MockSenderRecorder struct {
	mock *MockSender
}

func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &_MockSenderRecorder{mock}
	return mock
}

func (_m *MockSender) EXPECT() *_MockSenderRecorder {
	return _m.recorder
}

func (_m *MockSender) SendEmail(_param0 string, _param1 string, _param2 string) {
	_m.ctrl.Call(_m, "SendEmail", _param0, _param1, _param2)
}

func (_mr *_MockSenderRecorder) SendEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SendEmail", arg0, arg1, arg2)
}
